file_paths:
    sxrd_cpf_alpha_results_file: ../../SXRD_results/diamond_2022_additional/texture-studies/{experiment_number:06d}-stage-scan/sample_4/alpha/{experiment_number:06d}_texture_strength.txt
# File path to the SXRD texture results for the alpha-phase, refined using Continuous_Peak_fit with Fourier peak analysis.

    sxrd_cpf_beta_results_file: ../../SXRD_results/diamond_2022_additional/texture-studies/{experiment_number:06d}-stage-scan/sample_4/beta/{experiment_number:06d}_texture_strength.txt
# File path to the SXRD texture results for the beta-phase, refined using Continuous_Peak_fit with Fourier peak analysis.

    output_folder: ../../SXRD_results/diamond_2022_additional/texture-studies/112750-stage-scan/sample_4/texture_strength_comparison/
# File path to output folder for saving the results and figure images from the analysis.
    
user_inputs:
    sxrd_experiment_number: 112750
# Experiment number for the SXRD results.
    
    phase_1: alpha
# Name of phase 1    
    
    phase_2: beta
# Name of phase 2

    shape_vertical: 9
# Number of vertical synchrotron measurements

    shape_horizontal: 10
# Number of horizontal synchrotron measurements

    step_size: 0.5
# Step size of stage scan synchrotron measurements